titleOnly: true
types:
  - deps
  - improve
  - ops
  - tests       # plural form of the default "test"
  # defaults
  - feat
  - fix
  - improvement
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
